### ISSUE TITLE
Error: Unable to install App

### ISSUE THREAD

**Issue by scrappyTURTLEcom** [YAtechnologies/GoogleMaps-SP#1]
My first post on github: I added the GoogleMaps-SP Swift Package to my app. Both Google Maps and Google Places run perfectly on Simulator... But When installing the app on device, it builds successfully, it goes thru copying all the files to iPhone, and at the end it gives the error "Unable to Install App".

If I remove the GoogleMaps-SP Swift Package from my app, and off course delete all references to Google Maps, I can build, install on iPhone, and run my app with no problem. So it has something to do with the GoogleMaps-SP Swift Package.

Even though in the error details, it says, "No code signature found"... I don't have any problems with code signing.

error details:

Unable to install "app"
Domain: com.apple.dt.MobileDeviceErrorDomain
Code: -402620388
--
No code signature found.
Domain: com.apple.dt.MobileDeviceErrorDomain
Code: -402620388
User Info: {
    DVTRadarComponentKey = 261622;
    MobileDeviceErrorCode = "(0xE800801C)";
    "com.apple.dtdevicekit.stacktrace" = (
	0   DTDeviceKitBase                     0x000000011e58293f DTDKCreateNSErrorFromAMDErrorCode + 220
	1   DTDeviceKitBase                     0x000000011e5c1124 __90-[DTDKMobileDeviceToken installApplicationBundleAtPath:withOptions:andError:withCallback:]_block_invoke + 155
	2   DVTFoundation                       0x0000000101463b43 DVTInvokeWithStrongOwnership + 71
	3   DTDeviceKitBase                     0x000000011e5c0e65 -[DTDKMobileDeviceToken installApplicationBundleAtPath:withOptions:andError:withCallback:] + 1440
	4   IDEiOSSupportCore                   0x000000011e431d28 __118-[DVTiOSDevice(DVTiPhoneApplicationInstallation) processAppInstallSet:appUninstallSet:installOptions:completionBlock:]_block_invoke.292 + 3513
	5   DVTFoundation                       0x00000001015922aa __DVT_CALLING_CLIENT_BLOCK__ + 7
	6   DVTFoundation                       0x0000000101593ecc __DVTDispatchAsync_block_invoke + 1191
	7   libdispatch.dylib                   0x00007fff71abc6c4 _dispatch_call_block_and_release + 12
	8   libdispatch.dylib                   0x00007fff71abd658 _dispatch_client_callout + 8
	9   libdispatch.dylib                   0x00007fff71ac2c44 _dispatch_lane_serial_drain + 597
	10  libdispatch.dylib                   0x00007fff71ac35d6 _dispatch_lane_invoke + 363
	11  libdispatch.dylib                   0x00007fff71accc09 _dispatch_workloop_worker_thread + 596
	12  libsystem_pthread.dylib             0x00007fff71d17a3d _pthread_wqthread + 290
	13  libsystem_pthread.dylib             0x00007fff71d16b77 start_wqthread + 15
);
}
--

System Information

macOS Version 10.15.7 (Build 19H2)
Xcode 12.0.1 (17220)
iOS 14.0.1 running on iPhone SE

**Comment by karimhm** [comment]
Does this happen on apps downloaded from TestFlight?

**Comment by scrappyTURTLEcom** [comment]
No, the app is in early development phase.

**Comment by scrappyTURTLEcom** [comment]
Found the solution. Apparently this is a known (SR-13343) in Xcode 12. It has to do with "SwiftPM binaryTarget dependency and code signing", where Xcode fails to sign the frameworks that are provided by SwiftPM.

See this link: https://forums.swift.org/t/swiftpm-binarytarget-dependency-and-code-signing/38953

If you read thru you will find a link to the work around, by adding a script to the build phase of the target:

Work Around: https://pspdfkit.com/guides/ios/current/knowledge-base/library-not-found-swiftpm/

I just added the script to my app, everything is now good!

Thanks,

Soheil

**Comment by karimhm** [comment]
Maybe making the libraries as static libraries rather than dynamic ones would solve the problem.

**Comment by scrappyTURTLEcom** [comment]
Is this issue fixed in the 4.0.0 release?

**Comment by karimhm** [comment]
> Is this issue fixed in the 4.0.0 release?

No
