### ISSUE TITLE
building for simulator iPhone 12 Pro max give error

### ISSUE THREAD

**Issue by kjoe07** [YAtechnologies/GoogleMaps-SP#13]
building for iPhone not error but building for iPhone simulator give this errors in the picture.
![Captura de Pantalla 2021-05-26 a la(s) 7 17 17 p  m](https://user-images.githubusercontent.com/3653060/119743265-7f2cb280-be57-11eb-9ff4-d6d232ff6be9.png)
Undefined symbol: _OBJC_CLASS_$_GMSServices
Undefined symbol: _OBJC_CLASS_$_GMSMapView
Undefined symbol: _OBJC_CLASS_$_GMSCircle
Undefined symbol: _GMSProject
Undefined symbol: _OBJC_CLASS_$_GMSCameraUpdate
Undefined symbol: _OBJC_CLASS_$_GMSPolyline
Undefined symbol: _OBJC_CLASS_$_GMSCoordinateBounds
Undefined symbol: _OBJC_CLASS_$_GMSPolygon
Undefined symbol: _OBJC_CLASS_$_GMSMarker
Undefined symbol: _OBJC_CLASS_$_GMSCameraPosition
Undefined symbol: _OBJC_CLASS_$_GMSMutablePath
this is Xcode output in error 

ld: warning: ignoring file /Users/kjoe/Library/Developer/Xcode/DerivedData/OnRoad-cvupkmnytuaneydhjuxztnopypjs/Build/Products/Release-iphonesimulator/GoogleMapsBase.framework/GoogleMapsBase, building for iOS Simulator-arm64 but attempting to link with file built for iOS Simulator-x86_64
ld: warning: ignoring file /Users/kjoe/Library/Developer/Xcode/DerivedData/OnRoad-cvupkmnytuaneydhjuxztnopypjs/Build/Products/Release-iphonesimulator/GoogleMapsM4B.framework/GoogleMapsM4B, building for iOS Simulator-arm64 but attempting to link with file built for iOS Simulator-x86_64
ld: warning: ignoring file /Users/kjoe/Library/Developer/Xcode/DerivedData/OnRoad-cvupkmnytuaneydhjuxztnopypjs/Build/Products/Release-iphonesimulator/GooglePlaces.framework/GooglePlaces, building for iOS Simulator-arm64 but attempting to link with file built for iOS Simulator-x86_64
ld: warning: ignoring file /Users/kjoe/Library/Developer/Xcode/DerivedData/OnRoad-cvupkmnytuaneydhjuxztnopypjs/Build/Products/Release-iphonesimulator/GoogleMaps.framework/GoogleMaps, building for iOS Simulator-arm64 but attempting to link with file built for iOS Simulator-x86_64
ld: warning: ignoring file /Users/kjoe/Library/Developer/Xcode/DerivedData/OnRoad-cvupkmnytuaneydhjuxztnopypjs/Build/Products/Release-iphonesimulator/GoogleMapsCore.framework/GoogleMapsCore, building for iOS Simulator-arm64 but attempting to link with file built for iOS Simulator-x86_64
Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_GMSServices", referenced from:
      objc-class-ref in AppDelegate.o
  "_OBJC_CLASS_$_GMSMapView", referenced from:
      objc-class-ref in RastreoViewController.o
  "_OBJC_CLASS_$_GMSCircle", referenced from:
      objc-class-ref in RastreoViewController.o
  "_GMSProject", referenced from:
      -[GMUClusterItemQuadItem initWithClusterItem:] in GoogleMapsUtils(GMUNonHierarchicalDistanceBasedAlgorithm.o)
      -[GMUNonHierarchicalDistanceBasedAlgorithm clustersAtZoom:] in GoogleMapsUtils(GMUNonHierarchicalDistanceBasedAlgorithm.o)
  "_OBJC_CLASS_$_GMSCameraUpdate", referenced from:
      objc-class-ref in TripView.o
      objc-class-ref in RastreoViewController.o
      objc-class-ref in TripsListTableViewCell.o
      objc-class-ref in GeoZoneViewController.o
  "_OBJC_CLASS_$_GMSPolyline", referenced from:
      objc-class-ref in TripView.o
      objc-class-ref in RastreoViewController.o
      objc-class-ref in TripsListTableViewCell.o
  "_OBJC_CLASS_$_GMSCoordinateBounds", referenced from:
      objc-class-ref in TripView.o
      objc-class-ref in RastreoViewController.o
      objc-class-ref in TripsListTableViewCell.o
      objc-class-ref in GeoZoneViewController.o
      objc-class-ref in GoogleMapsUtils(GMUDefaultClusterRenderer.o)
  "_OBJC_CLASS_$_GMSPolygon", referenced from:
      objc-class-ref in RastreoViewController.o
      objc-class-ref in GeoZoneViewController.o
  "_OBJC_CLASS_$_GMSMarker", referenced from:
      objc-class-ref in TripView.o
      objc-class-ref in RastreoViewController.o
      objc-class-ref in TripsListTableViewCell.o
      objc-class-ref in NotificationDetailView.o
      objc-class-ref in GeoZoneViewController.o
      objc-class-ref in FilterViewController.o
      objc-class-ref in GoogleMapsUtils(GMUDefaultClusterRenderer.o)
      ...
  "_OBJC_CLASS_$_GMSCameraPosition", referenced from:
      objc-class-ref in TripView.o
      objc-class-ref in RastreoViewController.o
      objc-class-ref in NotificationDetailView.o
  "_OBJC_CLASS_$_GMSMutablePath", referenced from:
      objc-class-ref in TripView.o
      objc-class-ref in RastreoViewController.o
      objc-class-ref in TripsListTableViewCell.o
      objc-class-ref in GeoZoneViewController.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

the project is with Xcode 12.5

**Comment by karimhm** [comment]
@kjoe07 Can you include a sample project?

**Comment by kjoe07** [comment]
sorry but no could build a sample project this is a old project in production migrated from cocoaPods to SPM and can't provide and example, building for iPhone is right, but building for simulator failed with that strange errors.

**Comment by karimhm** [comment]
> sorry but no could build a sample project this is a old project in production migrated from cocoaPods to SPM and can't provide and example, building for iPhone is right, but building for simulator failed with that strange errors.

I tried the package with a fresh project created with `Xcode 12.5 (12E262)` on a simulator and on a real device and they both worked without problems. 

This might occur because of the project old configuration.

**Comment by karimhm** [comment]
Closed to to inactivity

**Comment by mvn-thienluong-dn** [comment]
@karimhm Same of my problem, Xcode 13
