### ISSUE TITLE
Checksums aren't same as 'make_xcframework.sh' gives

### ISSUE THREAD

**Issue by Scvairy** [YAtechnologies/GoogleMaps-SP#2]
I tried your script to pack google maps into XCFrameworks myself, but on download Xcode says that checksums are different from what it counted.
I downloaded by url and counted checksum of dowloaded (by command in the script and by `swift package compute-checksum ./GoogleMaps.xcframework-4.0.0.zip >> checksum_4_0_0`), and it was the same as in package.swift.

What could I do wrong?

**Comment by karimhm** [comment]
Where are you hosting the XCFramework `zip` files?

**Comment by Scvairy** [comment]
On in-house gitlab server, as an attachment to release.

**Comment by karimhm** [comment]
The URL of the XCFramework `zip` files must be publicly available since at the moment Xcode does not support any mechanism of authentication.

**Comment by karimhm** [comment]
Why you don't use the generated checksums found within `checksum` file?

**Comment by Scvairy** [comment]
I did use them, but the error occurred. I tried to check if downloaded files have the same checksums - and they do. But Xcode says opposite

**Comment by Scvairy** [comment]
> The URL of the XCFramework `zip` files must be publicly available since at the moment Xcode does not support any mechanism of authentication.

Thank you! That was the problem. Xcode downloaded login page (and obviously checksum was wrong)

**Comment by karimhm** [comment]
> > The URL of the XCFramework `zip` files must be publicly available since at the moment Xcode does not support any mechanism of authentication.
> 
> Thank you! That was the problem. Xcode downloaded login page (and obviously checksum was wrong)

One way to protect the URLs is by using [HTTP Basic Authentication](https://en.wikipedia.org/wiki/Basic_access_authentication).

Example:
```swift
.binaryTarget(
    name: "GoogleMaps",
    url: "https://username:password@example.com/GoogleMaps-SP/4.0.0/GoogleMaps.xcframework.zip",
    checksum: "xxxxx...."
)
```
