### ISSUE TITLE
Release Google Maps iOS SDK version 6.0.1-beta

### ISSUE THREAD

**Issue by karimhm** [YAtechnologies/GoogleMaps-SP#24]
[Google Maps SDK for iOS](https://developers.google.com/maps/documentation/ios-sdk/start) and [Google Places SDK for iOS](https://developers.google.com/maps/documentation/places/ios-sdk/start) version **6.0.1-beta** have been officially released by Google but not yet available here.

**Comment by AdieOlami** [comment]
Hi @karimhm is there any update on this?
