### ISSUE TITLE
no shared framework schemes

### ISSUE THREAD

**Issue by hasnain-mobimeo** [YAtechnologies/GoogleMaps-SP#28]
Hey 👋 
I am trying to integrate using the following in the Carfile
`github "YAtechnologies/GoogleMaps-SP" "6.0.0"`
to build dependencies for my packages 
but upon building, i get an error 
```
*** Skipped building GoogleMaps-SP due to the error:
▸ Dependency "GoogleMaps-SP" has no shared framework schemes for any of the platforms: iOS 
```
what am I doing wrong here?

My Xcode version is 13

**Comment by karimhm** [comment]
This repository contains only a [Swift package](https://www.swift.org/package-manager/) for Google Maps iOS. Carthage is not supported. To use Google Maps with Carthage you must use [Google's official](https://developers.google.com/maps/documentation/ios-sdk/start#use-carthage) Carthage build.
`binary "https://dl.google.com/geosdk/GoogleMaps.json" == 6.0.0`
