### ISSUE TITLE
autocompleteQuery has no member GMSPlacesClient

### ISSUE THREAD

**Issue by elmysf** [YAtechnologies/GoogleMaps-SP#30]
I'm creating place autocomplete in SwiftUI, using this SPM but  '**autocompleteQuery**' not found.
if you use **cocoapods** google maps, '**autocompleteQuery**' is ready, nothing in this SPM.

**_i hope you upgrade this spm, beacuse i really need this spm for my app_**
<img width="318" alt="Screen Shot 2022-01-11 at 15 01 47" src="https://user-images.githubusercontent.com/37185272/148904975-123d0895-f37a-4f37-af88-e76f53537dea.png">

**### _This sample code using GoogleMaps-SP SPM, for autocomplete place searching_**
[FindPlace.zip](https://github.com/YAtechnologies/GoogleMaps-SP/files/7844943/FindPlace.zip)

I'm using SPM Version 6.0.0

**_I really need this urgently for my app, because my app will be update in app store for many bug_**

**Comment by karimhm** [comment]
@elmysf The `autocompleteQuery:bounds:filter:callback` method is a deprecated method that goes way back to _Google Places iOS SDK 3.0.0_ The method was removed in _Google iOS Places SDK 4.0.0_.

The deprecation message says
```
"Method deprecated in favor of findAutocompletePredictionsFromQuery:filter:sessionToken:callback"
```

You have 2 options:

- Update your code to use the new replacement method `findAutocompletePredictionsFromQuery:filter:sessionToken:callback` _(recommended)_
- Use version 3.10.0 of Google Places iOS SDK (The sample you provided does use version 6.0.0).
