### ISSUE TITLE
Library fails to build on iOS Simulator-arm64

### ISSUE THREAD

**Issue by SzGajdzica** [YAtechnologies/GoogleMaps-SP#32]
Im getting this output when trying to build for ios simulator
I think it may be cause im using m1 mac (on previous mac with intel, did not have such issues)

`ld: warning: ld: warning: ignoring file /Users/szymon/Library/Developer/Xcode/DerivedData/gps-coordinates-ios-gejaxefktgbviicvhqytrdpzbosq/Build/Products/Debug-iphonesimulator/GoogleMapsBase.framework/GoogleMapsBase, building for iOS Simulator-arm64 but attempting to link with file built for iOS Simulator-x86_64
ignoring file /Users/szymon/Library/Developer/Xcode/DerivedData/gps-coordinates-ios-gejaxefktgbviicvhqytrdpzbosq/Build/Products/Debug-iphonesimulator/GoogleMaps.framework/GoogleMaps, building for iOS Simulator-arm64 but attempting to link with file built for iOS Simulator-x86_64
ld: warning: ignoring file /Users/szymon/Library/Developer/Xcode/DerivedData/gps-coordinates-ios-gejaxefktgbviicvhqytrdpzbosq/Build/Products/Debug-iphonesimulator/GoogleMapsCore.framework/GoogleMapsCore, building for iOS Simulator-arm64 but attempting to link with file built for iOS Simulator-x86_64
Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_GMSMapView", referenced from:
      objc-class-ref in MapView.o
  "_OBJC_CLASS_$_GMSCameraUpdate", referenced from:
      objc-class-ref in GoogleMapViewCompat.o
  "_OBJC_CLASS_$_GMSCoordinateBounds", referenced from:
      objc-class-ref in GoogleMapViewCompat.o
  "_OBJC_CLASS_$_GMSMapStyle", referenced from:
      objc-class-ref in GoogleMapViewCompat.o
  "_OBJC_CLASS_$_GMSCameraPosition", referenced from:
      objc-class-ref in GoogleMapViewCompat.o
  "_OBJC_CLASS_$_GMSMarker", referenced from:
      objc-class-ref in GoogleMapViewCompat.o
      objc-class-ref in LocationExtensions.o
  "_OBJC_CLASS_$_GMSServices", referenced from:
      objc-class-ref in MApp.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
`

**Comment by karimhm** [comment]
You are correct this error is happening due to M1 Macs. This issue was already reported #22
