### ISSUE TITLE
Duplicated in my app extension.

### ISSUE THREAD

**Issue by Neilfau** [YAtechnologies/GoogleMaps-SP#4]
Hi... ive being using the this package in my app and its all been working great. I recently added a widget extension which has no dependencies at all but for some reason this package is being added to the extension and the main app. When I try to upload to the App Store I get the error:

<img width="667" alt="Screenshot 2021-01-15 at 14 41 11" src="https://user-images.githubusercontent.com/1814989/104733952-c2f00c80-573f-11eb-85e7-b598970f83bf.png">

Any ideas what is causing this and how I can fix it??

**Comment by Neilfau** [comment]
I found the solution it was adding a post action build script:

```
rm -rf "${TARGET_BUILD_DIR}/${PRODUCT_NAME}.app/PlugIns/GoogleMaps.framework"
rm -rf "${TARGET_BUILD_DIR}/${PRODUCT_NAME}.app/PlugIns/GoogleMapsBase.framework"
rm -rf "${TARGET_BUILD_DIR}/${PRODUCT_NAME}.app/PlugIns/GoogleMapsCore.framework"
rm -rf "${TARGET_BUILD_DIR}/${PRODUCT_NAME}.app/Frameworks/GoogleMaps.framework"
rm -rf "${TARGET_BUILD_DIR}/${PRODUCT_NAME}.app/Frameworks/GoogleMapsBase.framework"
rm -rf "${TARGET_BUILD_DIR}/${PRODUCT_NAME}.app/Frameworks/GoogleMapsCore.framework"
```

**Comment by karimhm** [comment]
This happen due to this bug [SR-13840](https://bugs.swift.org/browse/SR-13840).

**Comment by CollinAlpert** [comment]
As of Xcode 12.5 this issue is also fixed.
