### ISSUE TITLE
How Generate Yassir link using user position and destination coordinates

### ISSUE THREAD

**Issue by Sofiane23i** [YAtechnologies/GoogleMaps-SP#47]
Hi, 

I'm working on a map service application and i would like to use Yassir service. 

Is there a method to generate a link request for Yassir using user and destinations coordinates , like in google maps direction api  ?
(https://www.google.com/maps/dir/?api=1&origin=34.1030032,-118.41046840000001&destination=34.059808,-118.368152) 

thank you

**Comment by karimhm** [comment]
> Hi,
> 
> I'm working on a map service application and i would like to use Yassir service.
> 
> Is there a method to generate a link request for Yassir using user and destinations coordinates , like in google maps direction api ? (https://www.google.com/maps/dir/?api=1&origin=34.1030032,-118.41046840000001&destination=34.059808,-118.368152)
> 
> thank you

Is this question related to **GoogleMaps** or Yassir mobile application?

**Comment by Sofiane23i** [comment]
Hi, 

The question is related to Yassir application, I want to call Yassir application automatically  from an external application using coordinates request (current and destination positions)

In the example above of google maps api, using the link we call google maps direction api automatically from external application using coordinates. is there an api for Yassir that do the same thing ?

**Comment by karimhm** [comment]
> Hi,
> 
> The question is related to Yassir application, I want to call Yassir application automatically from an external application using coordinates request (current and destination positions)
> 
> In the example above of google maps api, using the link we call google maps direction api automatically from an external application using coordinates. is there an api for Yassir that do the same thing ?

I believe there is none at the moment.

**Comment by Sofiane23i** [comment]
Thank you for your response

**Comment by Sofiane23i** [comment]
I think this feature named Deeplinking, it will be a good feature to integrate for us and for Yassir company.
