### ISSUE TITLE
When using  Googlemaps-SP in a framework, I get this runtime error

### ISSUE THREAD

**Issue by DubonYaar** [YAtechnologies/GoogleMaps-SP#5]
**Adding Googlemaps-SP to my Framework result in this runtime error** 

dyld: Library not loaded: @rpath/GoogleMaps.framework/GoogleMaps
  Referenced from: /private/var/containers/Bundle/Application/44EBC519-F1CD-4C1A-9D9E-C6845E62CCFB/SomeApp.app/SomeApp
  Reason: image not found
dyld: launch, loading dependent libraries
DYLD_LIBRARY_PATH=/usr/lib/system/introspection
DYLD_INSERT_LIBRARIES=/Developer/usr/lib/libBacktraceRecording.dylib:/Developer/usr/lib/libMainThreadChecker.dylib:/Developer/Library/PrivateFrameworks/DTDDISupport.framework/libViewDebuggerSupport.dylib:/Developer/Library/PrivateFrameworks/GPUTools.framework/libglInterpose.dylib:/usr/lib/libMTLCapture.dylib

**Comment by karimhm** [comment]
What Xcode version?.
Adding a sample project would help too.

**Comment by ArshAulakh59** [comment]
Was a solution found for this? I'm facing the same issue.

**Comment by karimhm** [comment]
> Was a solution found for this? I'm facing the same issue.

What Xcode version?
Adding a sample project would help finding a solution.

**Comment by ArshAulakh59** [comment]
> > Was a solution found for this? I'm facing the same issue.
> 
> What Xcode version?
> Adding a sample project would help finding a solution.

I'm on Xcode 12.3. Sure. Let me make a sample ready for you. Will post here.

**Comment by ArshAulakh59** [comment]
> I'm on Xcode 12.3. Sure. Let me make a sample for you. Will post here.

Here's the sample. 
[ErrorTest.zip](https://github.com/YAtechnologies/GoogleMaps-SP/files/6038607/ErrorTest.zip)

Sample seems to be working. Will try to figure out why it isn't working in my project and update here when I find something.

**Comment by ArshAulakh59** [comment]
I was able to fix this by changing my package's Package.swift `products` from
`.library(name: "SamplePackage", type: .dynamic, targets: ["SamplePackage"]),`
to
`.library(name: "SamplePackage", targets: ["SamplePackage"]),`
i.e removing the `type: .dynamic` part.
